export const sponsors = [
  {
    id: 1,
    name: 'Miasto Ostróda',
    src: '/miasto-ostroda.JPG',
    url: 'https://www.ostroda.pl',
  },
  {
    id: 2,
    name: 'Ostródzkie Centrum Sportu i Rekreacji',
    src: '/ocsir.png',
    url: 'https://ocsir.pl',
  },
  {
    id: 3,
    name: 'Powiat Ostródzki',
    src: '/powiat-ostroda.jpg',
    url: 'https://www.powiat.ostroda.pl/?rCH=2',
  },
  {
    id: 4,
    name: 'Łukosz',
    src: '/lukosz.jpg',
    url: 'http://www.lukosz.pl/pl',
  },
  {
    id: 5,
    name: 'EuroBud – rusztowania',
    src: '/eurobud.png',
    url: 'https://eurobud-rusztowania.pl',
  },
  {
    id: 6,
    name: 'Yoona',
    src: '/yoona.jpg',
    url: 'https://yoona.pl',
  },
  {
    id: 7,
    name: 'Garnek Brukarstwo',
    src: '/garnek-brukarstwo.png',
    url: 'https://www.facebook.com/garnekbrukarstwo/',
  },
  {
    id: 8,
    name: 'IMR Detailing',
    src: '/imr-detailing.jpg',
    url: 'https://www.facebook.com/IMRdetailing/?locale=pl_PL',
  },
  {
    id: 9,
    name: 'AGAT',
    src: '/agat.png',
    url: '',
  },
  {
    id: 10,
    name: 'Xtreme fitness',
    src: '/xtreme-fitness.PNG',
    url: 'https://xtremefitness.pl/ostroda',
  },
  {
    id: 11,
    name: 'Godlewski',
    src: '/godlewski.jpg',
    url: 'https://www.dzwigi-godlewski.pl',
  },
  {
    id: 12,
    name: 'SanBiagio',
    src: '/san-biagio.jpg',
    url: 'https://www.sanbiagio.pl',
  },
  {
    id: 13,
    name: 'Podmar',
    src: '/podmar.jpg',
    url: 'https://www.materialybudowlane-podmar.com.pl',
  },
];
