export const blogPosts = [
  {
    id: 1,
    title:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse suscipit.',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam urna magna, id feugiat quam fermentum eget. Cras at pretium ex. Suspendisse euismod dolor sed tortor tincidunt fermentum. Mauris non nisl sit amet urna tincidunt eleifend. Aliquam luctus, est at consectetur commodo, risus quam euismod nisl, non efficitur nulla nibh eu ex. Integer vitae dui vitae nibh iaculis euismod. Sed vitae ullamcorper massa. Etiam mauris mi, maximus sit amet enim sit amet, suscipit gravida enim. Pellentesque in leo nibh. Vestibulum efficitur, diam id dictum sodales, massa massa commodo urna, non hendrerit tortor tortor vel magna. Integer luctus ligula eget sapien tempor, vel porttitor dolor rhoncus. Sed dignissim eleifend libero. Fusce tempus vehicula tristique. Mauris a velit sapien. Duis vestibulum placerat ex nec maximus. Nulla sagittis in nisl vel auctor. Pellentesque lacinia vestibulum velit, non dapibus massa molestie ac. Ut sed tincidunt ante. Sed euismod nisi a tortor suscipit sodales. Nullam non nisl dui. Curabitur pulvinar, lectus non ultrices dignissim, leo purus vulputate ante, vitae lacinia augue tortor non elit. Nam auctor ligula augue, quis mollis enim vestibulum sed. Nulla tincidunt ullamcorper velit. Integer placerat suscipit maximus. Pellentesque dapibus tortor ut ipsum egestas bibendum. Quisque lobortis arcu a mauris egestas, eget consectetur urna bibendum. Phasellus elit sapien, facilisis vitae massa non, euismod commodo magna. Aenean eu mattis dui. Sed tempus, nibh eget pulvinar cursus, quam lectus facilisis erat, vitae venenatis eros nulla ac felis. Sed ut lobortis lorem, a euismod quam. Nullam eu ultricies nulla, quis luctus urna. Phasellus tristique lacus at blandit interdum. Praesent pretium felis vitae quam mattis ornare. Suspendisse aliquet, nibh et vehicula faucibus, elit libero pharetra nunc, vel bibendum nisl nisl id felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque dapibus cursus neque id faucibus. Sed eget interdum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum posuere at dui non pretium. Cras porttitor dapibus diam, a pulvinar diam auctor quis. Praesent at lacus cursus, molestie enim auctor, elementum risus. Mauris rhoncus, nibh non imperdiet congue, tellus diam ullamcorper quam, euismod vehicula ex tortor quis mi. Sed ullamcorper risus non nibh fermentum pharetra. Vivamus sed quam non arcu tempus ultrices et vitae urna. In gravida ante eget tellus hendrerit, sed egestas justo ullamcorper. Cras rhoncus odio vitae convallis auctor. Vivamus faucibus sit amet diam pharetra fermentum. Morbi sit amet volutpat justo. Duis dictum tempus lorem euismod tincidunt. Vivamus auctor pretium nulla, eget luctus purus viverra quis.',
    author: 'Jan Kukielski',
    date: '12.05.2024',
    src: '/team_one.jpg',
  },
  {
    id: 2,
    title:
      'Lorem ipsum dolor, consectetur adipiscing elit. Suspendisse suscipit.',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam urna magna, id feugiat quam fermentum eget. Cras at pretium ex. Suspendisse euismod dolor sed tortor tincidunt fermentum. Mauris non nisl sit amet urna tincidunt eleifend. Aliquam luctus, est at consectetur commodo, risus quam euismod nisl, non efficitur nulla nibh eu ex. Integer vitae dui vitae nibh iaculis euismod. Sed vitae ullamcorper massa. Etiam mauris mi, maximus sit amet enim sit amet, suscipit gravida enim. Pellentesque in leo nibh. Vestibulum efficitur, diam id dictum sodales, massa massa commodo urna, non hendrerit tortor tortor vel magna. Integer luctus ligula eget sapien tempor, vel porttitor dolor rhoncus. Sed dignissim eleifend libero. Fusce tempus vehicula tristique. Mauris a velit sapien. Duis vestibulum placerat ex nec maximus. Nulla sagittis in nisl vel auctor. Pellentesque lacinia vestibulum velit, non dapibus massa molestie ac. Ut sed tincidunt ante. Sed euismod nisi a tortor suscipit sodales. Nullam non nisl dui. Curabitur pulvinar, lectus non ultrices dignissim, leo purus vulputate ante, vitae lacinia augue tortor non elit. Nam auctor ligula augue, quis mollis enim vestibulum sed. Nulla tincidunt ullamcorper velit. Integer placerat suscipit maximus. Pellentesque dapibus tortor ut ipsum egestas bibendum. Quisque lobortis arcu a mauris egestas, eget consectetur urna bibendum. Phasellus elit sapien, facilisis vitae massa non, euismod commodo magna. Aenean eu mattis dui. Sed tempus, nibh eget pulvinar cursus, quam lectus facilisis erat, vitae venenatis eros nulla ac felis. Sed ut lobortis lorem, a euismod quam. Nullam eu ultricies nulla, quis luctus urna. Phasellus tristique lacus at blandit interdum. Praesent pretium felis vitae quam mattis ornare. Suspendisse aliquet, nibh et vehicula faucibus, elit libero pharetra nunc, vel bibendum nisl nisl id felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque dapibus cursus neque id faucibus. Sed eget interdum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum posuere at dui non pretium. Cras porttitor dapibus diam, a pulvinar diam auctor quis. Praesent at lacus cursus, molestie enim auctor, elementum risus. Mauris rhoncus, nibh non imperdiet congue, tellus diam ullamcorper quam, euismod vehicula ex tortor quis mi. Sed ullamcorper risus non nibh fermentum pharetra. Vivamus sed quam non arcu tempus ultrices et vitae urna. In gravida ante eget tellus hendrerit, sed egestas justo ullamcorper. Cras rhoncus odio vitae convallis auctor. Vivamus faucibus sit amet diam pharetra fermentum. Morbi sit amet volutpat justo. Duis dictum tempus lorem euismod tincidunt. Vivamus auctor pretium nulla, eget luctus purus viverra quis.',
    author: 'Jan Kukielski',
    date: '11.05.2024',
    src: '/team_two.jpg',
  },
  {
    id: 3,
    title: 'Lorem ipsum dolor sit amet, suspendisse suscipit.',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam urna magna, id feugiat quam fermentum eget. Cras at pretium ex. Suspendisse euismod dolor sed tortor tincidunt fermentum. Mauris non nisl sit amet urna tincidunt eleifend. Aliquam luctus, est at consectetur commodo, risus quam euismod nisl, non efficitur nulla nibh eu ex. Integer vitae dui vitae nibh iaculis euismod. Sed vitae ullamcorper massa. Etiam mauris mi, maximus sit amet enim sit amet, suscipit gravida enim. Pellentesque in leo nibh. Vestibulum efficitur, diam id dictum sodales, massa massa commodo urna, non hendrerit tortor tortor vel magna. Integer luctus ligula eget sapien tempor, vel porttitor dolor rhoncus. Sed dignissim eleifend libero. Fusce tempus vehicula tristique. Mauris a velit sapien. Duis vestibulum placerat ex nec maximus. Nulla sagittis in nisl vel auctor. Pellentesque lacinia vestibulum velit, non dapibus massa molestie ac. Ut sed tincidunt ante. Sed euismod nisi a tortor suscipit sodales. Nullam non nisl dui. Curabitur pulvinar, lectus non ultrices dignissim, leo purus vulputate ante, vitae lacinia augue tortor non elit. Nam auctor ligula augue, quis mollis enim vestibulum sed. Nulla tincidunt ullamcorper velit. Integer placerat suscipit maximus. Pellentesque dapibus tortor ut ipsum egestas bibendum. Quisque lobortis arcu a mauris egestas, eget consectetur urna bibendum. Phasellus elit sapien, facilisis vitae massa non, euismod commodo magna. Aenean eu mattis dui. Sed tempus, nibh eget pulvinar cursus, quam lectus facilisis erat, vitae venenatis eros nulla ac felis. Sed ut lobortis lorem, a euismod quam. Nullam eu ultricies nulla, quis luctus urna. Phasellus tristique lacus at blandit interdum. Praesent pretium felis vitae quam mattis ornare. Suspendisse aliquet, nibh et vehicula faucibus, elit libero pharetra nunc, vel bibendum nisl nisl id felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque dapibus cursus neque id faucibus. Sed eget interdum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum posuere at dui non pretium. Cras porttitor dapibus diam, a pulvinar diam auctor quis. Praesent at lacus cursus, molestie enim auctor, elementum risus. Mauris rhoncus, nibh non imperdiet congue, tellus diam ullamcorper quam, euismod vehicula ex tortor quis mi. Sed ullamcorper risus non nibh fermentum pharetra. Vivamus sed quam non arcu tempus ultrices et vitae urna. In gravida ante eget tellus hendrerit, sed egestas justo ullamcorper. Cras rhoncus odio vitae convallis auctor. Vivamus faucibus sit amet diam pharetra fermentum. Morbi sit amet volutpat justo. Duis dictum tempus lorem euismod tincidunt. Vivamus auctor pretium nulla, eget luctus purus viverra quis.',
    author: 'Jan Kukielski',
    date: '01.05.2024',
    src: '/team_6.jpg',
  },
  {
    id: 4,
    title: 'Lorem sit amet, consectetur adipiscing elit. Suspendisse suscipit.',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam urna magna, id feugiat quam fermentum eget. Cras at pretium ex. Suspendisse euismod dolor sed tortor tincidunt fermentum. Mauris non nisl sit amet urna tincidunt eleifend. Aliquam luctus, est at consectetur commodo, risus quam euismod nisl, non efficitur nulla nibh eu ex. Integer vitae dui vitae nibh iaculis euismod. Sed vitae ullamcorper massa. Etiam mauris mi, maximus sit amet enim sit amet, suscipit gravida enim. Pellentesque in leo nibh. Vestibulum efficitur, diam id dictum sodales, massa massa commodo urna, non hendrerit tortor tortor vel magna. Integer luctus ligula eget sapien tempor, vel porttitor dolor rhoncus. Sed dignissim eleifend libero. Fusce tempus vehicula tristique. Mauris a velit sapien. Duis vestibulum placerat ex nec maximus. Nulla sagittis in nisl vel auctor. Pellentesque lacinia vestibulum velit, non dapibus massa molestie ac. Ut sed tincidunt ante. Sed euismod nisi a tortor suscipit sodales. Nullam non nisl dui. Curabitur pulvinar, lectus non ultrices dignissim, leo purus vulputate ante, vitae lacinia augue tortor non elit. Nam auctor ligula augue, quis mollis enim vestibulum sed. Nulla tincidunt ullamcorper velit. Integer placerat suscipit maximus. Pellentesque dapibus tortor ut ipsum egestas bibendum. Quisque lobortis arcu a mauris egestas, eget consectetur urna bibendum. Phasellus elit sapien, facilisis vitae massa non, euismod commodo magna. Aenean eu mattis dui. Sed tempus, nibh eget pulvinar cursus, quam lectus facilisis erat, vitae venenatis eros nulla ac felis. Sed ut lobortis lorem, a euismod quam. Nullam eu ultricies nulla, quis luctus urna. Phasellus tristique lacus at blandit interdum. Praesent pretium felis vitae quam mattis ornare. Suspendisse aliquet, nibh et vehicula faucibus, elit libero pharetra nunc, vel bibendum nisl nisl id felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque dapibus cursus neque id faucibus. Sed eget interdum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum posuere at dui non pretium. Cras porttitor dapibus diam, a pulvinar diam auctor quis. Praesent at lacus cursus, molestie enim auctor, elementum risus. Mauris rhoncus, nibh non imperdiet congue, tellus diam ullamcorper quam, euismod vehicula ex tortor quis mi. Sed ullamcorper risus non nibh fermentum pharetra. Vivamus sed quam non arcu tempus ultrices et vitae urna. In gravida ante eget tellus hendrerit, sed egestas justo ullamcorper. Cras rhoncus odio vitae convallis auctor. Vivamus faucibus sit amet diam pharetra fermentum. Morbi sit amet volutpat justo. Duis dictum tempus lorem euismod tincidunt. Vivamus auctor pretium nulla, eget luctus purus viverra quis.',
    author: 'Jan Kukielski',
    date: '04.05.2024',
    src: '/team_4.jpg',
  },
  {
    id: 5,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam urna magna, id feugiat quam fermentum eget. Cras at pretium ex. Suspendisse euismod dolor sed tortor tincidunt fermentum. Mauris non nisl sit amet urna tincidunt eleifend. Aliquam luctus, est at consectetur commodo, risus quam euismod nisl, non efficitur nulla nibh eu ex. Integer vitae dui vitae nibh iaculis euismod. Sed vitae ullamcorper massa. Etiam mauris mi, maximus sit amet enim sit amet, suscipit gravida enim. Pellentesque in leo nibh. Vestibulum efficitur, diam id dictum sodales, massa massa commodo urna, non hendrerit tortor tortor vel magna. Integer luctus ligula eget sapien tempor, vel porttitor dolor rhoncus. Sed dignissim eleifend libero. Fusce tempus vehicula tristique. Mauris a velit sapien. Duis vestibulum placerat ex nec maximus. Nulla sagittis in nisl vel auctor. Pellentesque lacinia vestibulum velit, non dapibus massa molestie ac. Ut sed tincidunt ante. Sed euismod nisi a tortor suscipit sodales. Nullam non nisl dui. Curabitur pulvinar, lectus non ultrices dignissim, leo purus vulputate ante, vitae lacinia augue tortor non elit. Nam auctor ligula augue, quis mollis enim vestibulum sed. Nulla tincidunt ullamcorper velit. Integer placerat suscipit maximus. Pellentesque dapibus tortor ut ipsum egestas bibendum. Quisque lobortis arcu a mauris egestas, eget consectetur urna bibendum. Phasellus elit sapien, facilisis vitae massa non, euismod commodo magna. Aenean eu mattis dui. Sed tempus, nibh eget pulvinar cursus, quam lectus facilisis erat, vitae venenatis eros nulla ac felis. Sed ut lobortis lorem, a euismod quam. Nullam eu ultricies nulla, quis luctus urna. Phasellus tristique lacus at blandit interdum. Praesent pretium felis vitae quam mattis ornare. Suspendisse aliquet, nibh et vehicula faucibus, elit libero pharetra nunc, vel bibendum nisl nisl id felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque dapibus cursus neque id faucibus. Sed eget interdum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum posuere at dui non pretium. Cras porttitor dapibus diam, a pulvinar diam auctor quis. Praesent at lacus cursus, molestie enim auctor, elementum risus. Mauris rhoncus, nibh non imperdiet congue, tellus diam ullamcorper quam, euismod vehicula ex tortor quis mi. Sed ullamcorper risus non nibh fermentum pharetra. Vivamus sed quam non arcu tempus ultrices et vitae urna. In gravida ante eget tellus hendrerit, sed egestas justo ullamcorper. Cras rhoncus odio vitae convallis auctor. Vivamus faucibus sit amet diam pharetra fermentum. Morbi sit amet volutpat justo. Duis dictum tempus lorem euismod tincidunt. Vivamus auctor pretium nulla, eget luctus purus viverra quis.',
    author: 'Jan Kukielski',
    date: '12.05.2024',
    src: '/team_5.jpg',
  },
];
